# tasks/linux.yml
---
- name: Copy JBoss EAP zip file to remote server
  ansible.builtin.copy:
    src: "/home/joy/ansible-hub/jboss-eap/jboss-eap-7.4.0.zip"  # Local path to the JBoss EAP zip file
    dest: "/tmp/jboss-eap.zip"  # Destination path on the remote server
    mode: '0644'
  become: true

- name: Ensure JBoss installation directory exists
  ansible.builtin.file:
    path: "{{ jboss_install_directory }}"
    state: directory
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: '0755'
  become: true

- name: Extract JBoss EAP zip file
  ansible.builtin.unarchive:
    src: "/tmp/jboss-eap.zip"
    dest: "{{ jboss_install_directory }}"
    remote_src: yes  # Tells Ansible that the file is already on the remote server
    creates: "{{ jboss_install_directory }}/bin/standalone.sh"  # Ensures the file is extracted only once
  become: true

- name: Set JBoss environment variables
  ansible.builtin.lineinfile:
    path: "/etc/profile"
    line: 'export JBOSS_HOME={{ jboss_install_directory }}'
    state: present
  become: true

- name: Ensure JBoss startup script is executable
  ansible.builtin.file:
    path: "{{ jboss_install_directory }}/bin/standalone.sh"
    mode: '0755'
  become: true

- name: Start JBoss EAP (Optional)
  ansible.builtin.shell:
    cmd: "{{ jboss_install_directory }}/bin/standalone.sh &"
  async: 30
  poll: 0
  become: true
